apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: aa9lbqqsr-nodejs 
  janus-idp.io/tekton: aa9lbqqsr-nodejs
  backstage.io/kubernetes-id: aa9lbqqsr-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aa9lbqqsr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml